/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertBox: typeof import('./components/common/AlertBox.vue')['default']
    AppDialogs: typeof import('./components/common/AppDialogs.vue')['default']
    BaseBadge: typeof import('./components/base/BaseBadge.vue')['default']
    BaseButton: typeof import('./components/base/BaseButton.vue')['default']
    BaseCard: typeof import('./components/base/BaseCard.vue')['default']
    BaseCheckbox: typeof import('./components/base/BaseCheckbox.vue')['default']
    BaseDropdown: typeof import('./components/base/BaseDropdown.vue')['default']
    BaseEmptyState: typeof import('./components/base/BaseEmptyState.vue')['default']
    BaseErrorState: typeof import('./components/base/BaseErrorState.vue')['default']
    BaseField: typeof import('./components/base/BaseField.vue')['default']
    BaseInput: typeof import('./components/base/BaseInput.vue')['default']
    BaseListContainer: typeof import('./components/base/BaseListContainer.vue')['default']
    BaseMarkdown: typeof import('./components/markdown/BaseMarkdown.vue')['default']
    BaseModal: typeof import('./components/base/BaseModal.vue')['default']
    BasePagination: typeof import('./components/base/BasePagination.vue')['default']
    BaseRadio: typeof import('./components/base/BaseRadio.vue')['default']
    BaseSelect: typeof import('./components/base/BaseSelect.vue')['default']
    BaseSkeleton: typeof import('./components/base/BaseSkeleton.vue')['default']
    BulkActions: typeof import('./components/common/BulkActions.vue')['default']
    BulkTagEditor: typeof import('./components/common/BulkTagEditor.vue')['default']
    CaseStemPanel: typeof import('./components/cases/CaseStemPanel.vue')['default']
    ChartCard: typeof import('./components/charts/ChartCard.vue')['default']
    DifficultyBadge: typeof import('./components/base/DifficultyBadge.vue')['default']
    DirectionalIcon: typeof import('./components/base/DirectionalIcon.vue')['default']
    DropZone: typeof import('./components/common/DropZone.vue')['default']
    ErrorBanner: typeof import('./components/common/ErrorBanner.vue')['default']
    ErrorBoundary: typeof import('./components/common/ErrorBoundary.vue')['default']
    ExpiryWarning: typeof import('./components/layout/ExpiryWarning.vue')['default']
    ExportButtons: typeof import('./components/common/ExportButtons.vue')['default']
    Footer: typeof import('./components/layout/Footer.vue')['default']
    FormGrid: typeof import('./components/common/FormGrid.vue')['default']
    ImportPreviewTable: typeof import('./components/common/ImportPreviewTable.vue')['default']
    LanguageSwitcher: typeof import('./components/layout/LanguageSwitcher.vue')['default']
    Layout: typeof import('./components/common/Layout.vue')['default']
    MarkdownEditor: typeof import('./components/markdown/MarkdownEditor.vue')['default']
    MarkdownToolbar: typeof import('./components/markdown/MarkdownToolbar.vue')['default']
    MobileBottomNav: typeof import('./components/layout/MobileBottomNav.vue')['default']
    ModerationCard: typeof import('./components/common/ModerationCard.vue')['default']
    Navbar: typeof import('./components/layout/Navbar.vue')['default']
    NavbarDropdown: typeof import('./components/layout/NavbarDropdown.vue')['default']
    NavbarUserMenu: typeof import('./components/layout/NavbarUserMenu.vue')['default']
    NotificationBell: typeof import('./components/layout/NotificationBell.vue')['default']
    PageHeader: typeof import('./components/common/PageHeader.vue')['default']
    PageShell: typeof import('./components/common/PageShell.vue')['default']
    ProgressBar: typeof import('./components/common/ProgressBar.vue')['default']
    QuestionNavDots: typeof import('./components/base/QuestionNavDots.vue')['default']
    ReviewItem: typeof import('./components/common/ReviewItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollToTop: typeof import('./components/common/ScrollToTop.vue')['default']
    ShortcutHint: typeof import('./components/common/ShortcutHint.vue')['default']
    SourceGridPicker: typeof import('./components/common/SourceGridPicker.vue')['default']
    StatTile: typeof import('./components/base/StatTile.vue')['default']
    TabStrip: typeof import('./components/common/TabStrip.vue')['default']
    ThemeDropdown: typeof import('./components/layout/ThemeDropdown.vue')['default']
    TimeAgo: typeof import('./components/common/TimeAgo.vue')['default']
    Timer: typeof import('./components/common/Timer.vue')['default']
    ToastContainer: typeof import('./components/common/ToastContainer.vue')['default']
  }
}
